# Generated by Django 5.1.1 on 2024-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
