# Generated by Django 5.1.1 on 2024-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answerset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
