# Generated by Django 5.1.1 on 2024-09-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answerset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerset',
            name='user_name',
            field=models.TextField(default='name', max_length=100),
        ),
    ]
