# Generated by Django 5.1.1 on 2024-12-31 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answerset_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionQuestionSetMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questionset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('question_set', 'question')},
            },
        ),
    ]
