"""sqlmodel

Revision ID: e22a281f6940
Revises: fd3ccd2a31e4
Create Date: 2025-05-13 01:52:44.309042

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e22a281f6940'
down_revision: Union[str, None] = 'fd3ccd2a31e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemcontestmapper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('contests', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('contests', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('problems', 'question',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('problems', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('problems', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('problems', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('problems', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('problems', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('submissions', 'contest_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'contest_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('problems', 'correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problems', 'option_d',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problems', 'option_c',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problems', 'option_b',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problems', 'option_a',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('problems', 'question',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('contests', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('contests', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('problemcontestmapper')
    # ### end Alembic commands ###
